# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 22, 4, 59, 8, 977914, tzinfo=utc)),
        ),
    ]
